// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenTypeKeyword-0]
	_ = x[tokenTypeIdent-1]
	_ = x[tokenTypeLit-2]
	_ = x[tokenTypeOp-3]
	_ = x[tokenTypeSymbol-4]
	_ = x[tokenTypeInvalid-5]
}

const _tokenType_name = "tokenTypeKeywordtokenTypeIdenttokenTypeLittokenTypeOptokenTypeSymboltokenTypeInvalid"

var _tokenType_index = [...]uint8{0, 16, 30, 42, 53, 68, 84}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
