// Code generated by "stringer -type=opType"; DO NOT EDIT.

package runtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[opTypeAddEq-0]
	_ = x[opTypeSubEq-1]
	_ = x[opTypeModEq-2]
	_ = x[opTypeAssign-3]
	_ = x[opTypeMultEq-4]
	_ = x[opTypeMod-5]
	_ = x[opTypeAdd-6]
	_ = x[opTypeMult-7]
	_ = x[opTypeInvalid-8]
}

const _opType_name = "opTypeAddEqopTypeSubEqopTypeModEqopTypeAssignopTypeMultEqopTypeModopTypeAddopTypeMultopTypeInvalid"

var _opType_index = [...]uint8{0, 11, 22, 33, 45, 57, 66, 75, 85, 98}

func (i opType) String() string {
	if i < 0 || i >= opType(len(_opType_index)-1) {
		return "opType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _opType_name[_opType_index[i]:_opType_index[i+1]]
}
