// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenTypeKeywordActor-0]
	_ = x[TokenTypeKeywordShow-1]
	_ = x[TokenTypeIdent-2]
	_ = x[TokenTypeLit-3]
	_ = x[TokenTypeOp-4]
	_ = x[TokenTypeSymbol-5]
	_ = x[TokenTypeInvalid-6]
}

const _TokenType_name = "TokenTypeKeywordActorTokenTypeKeywordShowTokenTypeIdentTokenTypeLitTokenTypeOpTokenTypeSymbolTokenTypeInvalid"

var _TokenType_index = [...]uint8{0, 21, 41, 55, 67, 78, 93, 109}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
