// Code generated by "stringer -type=ModuleItemType"; DO NOT EDIT.

package parse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModuleItemActor-0]
	_ = x[ModuleItemShow-1]
	_ = x[ModuleItemSend-2]
}

const _ModuleItemType_name = "ModuleItemActorModuleItemShowModuleItemSend"

var _ModuleItemType_index = [...]uint8{0, 15, 29, 43}

func (i ModuleItemType) String() string {
	if i < 0 || i >= ModuleItemType(len(_ModuleItemType_index)-1) {
		return "ModuleItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ModuleItemType_name[_ModuleItemType_index[i]:_ModuleItemType_index[i+1]]
}
